### ISSUE TITLE
template parse errors

### ISSUE THREAD

**Issue by arianvaldivieso** [exalif/angular-libs#12]
'breadcrums' is ot a known element?

As I can solve this error, I followed the example to the letter. I'm working with the angular version 7

**Comment by blackholegalaxy** [comment]
you have to use the proper element name in your template: `lib-breadcrumbs`. Also make sure you import the module properly.

**Comment by arianvaldivieso** [comment]
According to the documentation the component is called in this way:
<breadcrumbs> </ breadcrumbs>
but likewise marks error if I call it that way. I've already tried several ways and none works

**Comment by arianvaldivieso** [comment]
I've seen the error, thanks

**Comment by arianvaldivieso** [comment]
![imagen](https://user-images.githubusercontent.com/9378982/55521454-cee40a80-564e-11e9-9bef-928e80d45e10.png)

this is the error where I must import the module, since I have it imported into my router and it is all right

**Comment by blackholegalaxy** [comment]
you should import `BreadcrumbsModule` in the module where you also declare your event details component. You can also import `BreadcrumbsModule.forRoot()` in your `app.module.ts` to inject the service once at the root level.

**Comment by blackholegalaxy** [comment]
Since there is no new element, I close the issue. Please feel free to open again if it's not resolved.
