### ISSUE TITLE
Angular 17

### ISSUE THREAD

**Issue by Ocunidee** [exalif/angular-libs#122]
Hello,
Could the library support Angular 17?
Thanks in advance :)

**Comment by blackholegalaxy** [comment]
I have some time right now and will investigate angular 17. Did you have opportunity to test the latest package version in angular 17, to know if it works by any chance?

**Comment by Ocunidee** [comment]
Yes, I have. It seems to be working as expected :)

**Comment by blackholegalaxy** [comment]
Ok, good news. I will do some tests and then publish a v17 which satisfies new peer dependencies to avoid warnings. Thanks for your input :)

**Comment by Ocunidee** [comment]
Thanks :)

**Comment by blackholegalaxy** [comment]
Version 17.0.0 should be available. Due to a technical pb, had to bump mat-popover to 17.0.1. Will be synced later.

**Comment by Ocunidee** [comment]
Hi!
Thanks :)
It seems there's a node version issue (the pipeline didn't pass)

**Comment by blackholegalaxy** [comment]
On the lib? Everything passed properly. Are you talking in your project?

**Comment by Ocunidee** [comment]
Oh nevermind, it's because on npm the version 17 is tagged as next not latest, my bad :)
