### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by piernik** [exalif/angular-libs#3]
In readme You have `<breadcrumbs></breadcrumbs>`
I believe it's `<lib-breadcrumbs></lib-breadcrumbs>`

PS. great that You continue `ngx-breadcrumb` library <ok>

**Comment by blackholegalaxy** [comment]
You are right i'll fix that. No problem we were bored the lib doesn't evolve and adapt. So we took ownership :D

**Comment by blackholegalaxy** [comment]
Done :) Thanks for your issue :)
