### ISSUE TITLE
New version @exalif/ngx-breadcrumbs v8.0.0 throws error on startup (target entry-point has missing dependencies)

### ISSUE THREAD

**Issue by FloppyNotFound** [exalif/angular-libs#46]
Hi,
when I use the latest version of @exalif/ngx-breadcrumbs v8.0.0 I get an error on startup:

ERROR in The target entry-point "@exalif/ngx-breadcrumbs" has missing dependencies:     
 - lodash.template
 - lodash.templatesettings

Since Angular 9 changed the way it handled entrypoints, my suggestion is, that something needs to be reconfigured within your lib.
Can you please take a look at this?

**Comment by piernik** [comment]
Any news on this?

**Comment by blackholegalaxy** [comment]
I will have a look this week. We have two projects using this with angular 9 and no problem. Do you have lodash template installed in your project?

**Comment by FloppyNotFound** [comment]
This is a new dependency in this version, right?
I don't have lodash.template installed, maybe that's the problem then .. I will test this tomorrow.
& keep you posted.
Could you then please update the installation guide within the readme accordingly?

**Comment by blackholegalaxy** [comment]
In fact it was listed as peer dependency since beginning. Even at the point I forked the lib from the original repo.

It's mentionned top on requirements:

https://github.com/exalif/angular-libs/tree/master/projects/ngx-breadcrumbs#requirements

Could you test while having this installed and come back to me with result? I will try to get rid of lodash template this week.

**Comment by FloppyNotFound** [comment]
Hi,
I tested it with lodash.template installed and it works now.
Sorry, my bad, must have skipped that part within the installation guide, and since I upgraded from v7 to v8 it now became obligatory to install lodash.template, running the app failed .. ticket can be closed.

**Comment by blackholegalaxy** [comment]
Thanks for the feedback :)
