### ISSUE TITLE
Unable to use with IE11

### ISSUE THREAD

**Issue by kamcknig** [exalif/angular-libs#59]
When using angular 9 and targeting IE11, I get a syntax error  with vendor.js. When I remove this library, it fixes the issue.

**Comment by blackholegalaxy** [comment]
I will try to check but unfortunately, I don't have IE available. Maybe some polyfill is missing. Could you try to report here the exact error lines?

**Comment by kamcknig** [comment]
From my understanding it's because your module is shipped with esm2015 and fesm2015 bundles but not and esm5 bundle and so when setting my tsconfig to target es5 which is required for IE11 then when building for development mode it doesn't transpile the module. But when building for production mode it does get transpiled

When searching around, I found that you could change the babel config to go ahead and transpile during dev builds but I'm on angular 9 which doesn't use the previous build system so I can no longer do that with babel. 

The actual error is with the `class` keyword. I am not at a computer now to screenshot it but it's basically that IE11 doesn't recognize it

**Comment by kamcknig** [comment]
I have taken a screenshot of the error. It's a syntax error 1002
![2020-11-27 10_06_18-Window](https://user-images.githubusercontent.com/705490/100462554-702b9a00-3098-11eb-97ec-cdda4aff4603.png)

**Comment by blackholegalaxy** [comment]
Targetting ES5 is not a problem here. I use ES5 target on our main public facing website with no problem. If building in prod / dev is a different behavior on your side, then I'm afraid I can't fix anything on my side. Our libs are produced using ng-packagr which produce esm2015 and fesm2015 (and I think UMD ones). You should specifiy in your dev environment to use a more recent version of `module` in tsconfig. Even if the target stays at es5.

**Comment by kamcknig** [comment]
Unfortunately I'm not familiar enough with the build process and everything I've read for angular says that the module should provide the proper code. So I'm unsure what to do. Thanks anyway

**Comment by kamcknig** [comment]
It's also unclear how the `module` property would help since that just determines the module loading system which is common JS by default when the target is ES5 so that should be taken care of as I don't manually set that, but I believe setting that to any other value won't solve this issue

**Comment by blackholegalaxy** [comment]
I reached some colleagues here. Two things come in mind:

 - On ng-packgr version 10+, es5 modules are deprecated. https://github.com/ng-packagr/ng-packagr/issues/1732#issuecomment-678993120
 - To produce ngx-mat-popover (please confirm it's the right package), we used an earlier version.
 - On ngx-mat-popover 3.0.0 we used the newer version so it omitted older packages.

I just built a version 2.0.1 meant to be compatible with angular 9 and IE11. If you agree to give it a try it could be nice.

Unfortunately, since es5 seems to be deprecated, v3+ will not support IE11 or any browser requiring es5 modules. I will place a breaking change notice on README.

**Comment by kyle-mcknight** [comment]
Sure, I would give it a try

**Comment by kyle-mcknight** [comment]
2.0.1 works when using a tsconfig targets es5

**Comment by blackholegalaxy** [comment]
Perfect. Closing.
