### ISSUE TITLE
ngx-breadcrumbs - properties with underscores in resolved entity, are not printed

### ISSUE THREAD

**Issue by messyjoes1** [exalif/angular-libs#60]
When entity is resolved successfully, only properties without underscores will actually be replaced in final string.

breadcrumbs: '{{ entity.works }}'

breadcrumbs: '{{ entity.does_not_work }}'

**Comment by blackholegalaxy** [comment]
Version 9.0.1 is published now and should handle underscores properly.

**Comment by messyjoes1** [comment]
Hi, thanks for fast response

I tested but it still doesnt work:
'{{ entity.does_not_work }}' will print "Entity.does"

Seems that keyRegex also needs '_'

**Comment by blackholegalaxy** [comment]
Sorry. I changed it in keyRegex but forgot to push the second commit 🤦 
New version published as `9.0.2`, keep me posted of your findings.

**Comment by blackholegalaxy** [comment]
@messyjoes1  is the problem solved with my latest fix?

**Comment by messyjoes1** [comment]
Yes works great, thank you!
