### ISSUE TITLE
Problems with template-based breadcrumbs

### ISSUE THREAD

**Issue by maksym-plotnikov** [exalif/angular-libs#63]
Nice library and we really love to use it!
But we faced some weird issue:
- when we're trying to render breadcrumb name with a template syntax (e.g. breadcrumbs: '{{ person.name }}') we have problems with property names written in `snake_case` like: {{ entity.id_on_company }},   {{ device.serial_id_number }} etc. They just not being populated  and stay as a strings :(

Could You please take a look into this?

**Comment by maksym-plotnikov** [comment]
Funny thing that after another `yarn install` and  project restart it become working again! 
Damn Angular seems to mess it up!

**Comment by blackholegalaxy** [comment]
Indeed the issue #60 was about the same problem. Behavior was fixed to handle values containing underscores in version > `9.0.2`

**Comment by maksym-plotnikov** [comment]
Oh I got it! Thanks for an answer anyway!
