### ISSUE TITLE
[breadcrumbs] Breadcrumbs with the same text get filtered out

### ISSUE THREAD

**Issue by beyerleinf** [exalif/angular-libs#64]
Currently, breadcrumbs with the same text get filtered out by the `distinct` RxJS operator even if they're not on the same level. I don't think this is desirable since there can be use cases (like ours) where this is a possibility.

**Comment by blackholegalaxy** [comment]
Interesting case! I may remove distinct operator and let the operator be applied at app level if needed. Would this suit your needs?

**Comment by beyerleinf** [comment]
yeah that would be great

**Comment by blackholegalaxy** [comment]
Do you use breadcrumbs component or a custom component to display crumbs?

**Comment by beyerleinf** [comment]
I currently use a custom component and the service you provide.

**Comment by beyerleinf** [comment]
I think it would also be good if you provide a flag to toggle the `distinct` operator so it doesn't break existing apps/

**Comment by blackholegalaxy** [comment]
It's my plan to add this in Config service

**Comment by blackholegalaxy** [comment]
PR #65  on the way. If you want to test behavior while waiting for package to be published by my colleague.

**Comment by blackholegalaxy** [comment]
@beyerleinf version 9.1.0 should solve this problem :)

**Comment by beyerleinf** [comment]
Perfect, thank you very much! The PR looks great, will test on Monday morning :)

**Comment by beyerleinf** [comment]
Works perfectly! Btw, if you need any help with anything (unit tests, etc.), I might be able to help :)

**Comment by blackholegalaxy** [comment]
We indeed lack some unit tests on libs. Help on this would be appreciated. It's on my plate but hard to find the time these days :D

**Comment by beyerleinf** [comment]
I think I could help you out with that a bit :)

**Comment by blackholegalaxy** [comment]
That could be nice thanks!
