### ISSUE TITLE
Package not supporting Angular version higher than 12.0.0

### ISSUE THREAD

**Issue by gocampo-rmq** [exalif/angular-libs#76]
The current installation doesn't support Angular Common higher than v 12.0.0

![image](https://user-images.githubusercontent.com/87395141/126684732-b3f14746-6f22-4899-bf3b-f140e1964137.png)

Installation should support latest Angular version

**Comment by blackholegalaxy** [comment]
I will push an updated version later today. After testing, all seems ok with Angular 12 so I feel confident moving the peer dependency requirements.

**Comment by DerPeit** [comment]
Any news on this? It's not working with Angular 13, either, which has been released on Dec, 15th.

**Comment by blackholegalaxy** [comment]
Hi Guys. Sorry about this huge delay. Had a baby in the mean time. Everything should be in order now. Tested on our own project which was moved to angular 13 with no problem. If a problem occurs, please open a bug i'll fix this.
