### ISSUE TITLE
Angular 15

### ISSUE THREAD

**Issue by ravz** [exalif/angular-libs#93]
can you please update for Angular 15, I get peer dependency errors

**Comment by blackholegalaxy** [comment]
It was planned and will release this week :) As far as I could see so far, there is no compatibility issue and you can safely ignore dependencies errors.

**Comment by Ocunidee** [comment]
Hi!
Is there any news on the front of the update to Angular 15?

**Comment by Ocunidee** [comment]
Thanks a lot :)
